name: Deploy EKS Cluster with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: snack-tech

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3. Configurar o Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # 4. Criar o Bucket S3 para o Backend
    - name: Create S3 Backend Bucket
      run: |
        terraform init
        terraform apply -target=aws_s3_bucket.backend -auto-approve

    # 5. Reconfigurar o Backend do Terraform
    - name: Reconfigure Backend
      run: terraform init -reconfigure

    # 6. Validar o Terraform
    - name: Terraform Validate
      run: terraform validate

    # 7. Gerar o plano do Terraform
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # 8. Aplicar o plano do Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    # 9. Atualizar kubeconfig
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
